using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TaskManagerApi.Models;

public class TaskItem
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }  // Auto-generated by DB

    [Required]
    public string Title { get; set; } = string.Empty;

    public string? Description { get; set; }

    [Required]
    public TaskStatus Status { get; set; } = TaskStatus.Incomplete;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow; // auto default

    public int Position { get; set; }
}

public enum TaskStatus
{
    Incomplete = 0,
    InProgress = 1,
    Complete = 2
}
